// flow-typed signature: 74bcd15b2c1e3f5ecad62c5a7db4895a
// flow-typed version: <<STUB>>/styled-map_v^2.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-map/dist/index' {
  declare module.exports: any;
}

declare module 'styled-map/lib/index' {
  declare module.exports: any;
}

declare module 'styled-map/lib/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-map/dist/index.js' {
  declare module.exports: $Exports<'styled-map/dist/index'>;
}
declare module 'styled-map/lib/index.js' {
  declare module.exports: $Exports<'styled-map/lib/index'>;
}
declare module 'styled-map/lib/index.test.js' {
  declare module.exports: $Exports<'styled-map/lib/index.test'>;
}
